name: Upload Python Package

on:
    release:
        types: [created]

jobs:
    deploy_linux:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: "3.9"
            - name: Set up Node.js
              uses: actions/setup-node@v1
              env:
                  RUNNER_TEMP: /tmp
              with:
                  node-version: "14.x"
            - name: Install Python dependencies
              run: |
                  python -m venv venv
                  source venv/bin/activate
                  python -m pip install --upgrade pip wheel setuptools
                  pip install twine mkdocs mkdocs-material
            - name: Generate webpack bundle
              working-directory: ./bcml/assets
              run: |
                  npm install
                  ./node_modules/.bin/webpack --mode production
            - name: Build docs
              run: |
                  source venv/bin/activate
                  mkdocs build -d ./bcml/assets/help
            - name: Patch roead version
              run: sed -i 's/<0.10.4/0.10.4/g' Cargo.toml
            - uses: actions-rs/toolchain@v1
              name: Install Rust
              with:
                profile: minimal
                toolchain: nightly
                override: true
            - uses: messense/maturin-action@v1
              name: Publish with Maturin
              with:
                maturin-version: v0.12.20
                command: publish
                args: --no-sdist -u ${{ secrets.PYPI_USERNAME }} -p ${{ secrets.PYPI_PASSWORD }} --skip-existing
                rust-toolchain: nightly
    deploy_windows:
        runs-on: windows-2019
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3.9
              uses: actions/setup-python@v2
              with:
                  python-version: "3.9"
            - name: Set up Python 3.7
              uses: actions/setup-python@v2
              with:
                  python-version: "3.7"
            - name: Set up Python 3.8
              uses: actions/setup-python@v2
              with:
                  python-version: "3.8"
            - name: Set up Node.js
              uses: actions/setup-node@v1
              # env:
              #     RUNNER_TEMP: /tmp
              with:
                  node-version: "14.x"
            - name: Install Python dependencies
              run: |
                  python -m venv venv
                  venv\Scripts\activate.ps1
                  python -m pip install --upgrade pip wheel setuptools
                  pip install twine mkdocs mkdocs-material maturin
            - name: Generate webpack bundle
              working-directory: .\bcml\assets
              run: |
                  npm install
                  npm run build
            - name: Build docs
              run: |
                  venv\Scripts\activate.ps1
                  mkdocs build -d .\bcml\assets\help
            - uses: actions-rs/toolchain@v1
              name: Install Rust
              with:
                profile: minimal
                toolchain: nightly
                override: true
            - name: Publish with Maturin
              run: |
                  venv\Scripts\activate.ps1
                  maturin publish -f --no-sdist -u ${{ secrets.PYPI_USERNAME }} -p ${{ secrets.PYPI_PASSWORD }} --skip-existing
